-- ============================================================================
-- Mise à jour de la page Conditions (document « project_conditions »)
-- Texte officiel de la cliente (PDF « WEBSITE PROJECT DETAILS & CONDITIONS »).
-- ----------------------------------------------------------------------------
-- À exécuter dans Supabase → SQL Editor. Idempotent (remplace les sections).
-- Harmonisé avec les services mis à jour :
--   • « Design Blueprint »  → « Garage Design & Build Plan »
--   • « Design + Delivery » → « Design & Setup »
--   • zone de service : « throughout the Orlando area » (plus de « 20 miles »)
-- ============================================================================

-- 1) Intro + titre du document
update public.legal_documents
set title = jsonb_build_object('en', 'Website Project Details & Conditions', 'fr', 'Condiciones y compromisos del proyecto'),
    intro = jsonb_build_object(
      'en', $$We set clear expectations from day one, plan carefully, and guide your project from idea to completion — depending on the level of service you choose. These guidelines ensure a smooth, transparent, and well-managed experience. By engaging with Garage à la Carte, you agree to these project guidelines unless otherwise defined in a written agreement.$$,
      'fr', $$Definimos expectativas claras desde el primer día, planificamos con cuidado y acompañamos tu proyecto desde la idea hasta la entrega — según el nivel de servicio que elijas. Estas pautas garantizan una experiencia fluida, transparente y bien gestionada. Al trabajar con Garage à la Carte, aceptas estas pautas salvo acuerdo escrito en sentido contrario.$$
    ),
    is_active = true,
    updated_at = now()
where document_key = 'project_conditions';

-- 2) Remplacement complet des sections par la version détaillée de la cliente
delete from public.legal_sections
where document_id = (select id from public.legal_documents where document_key = 'project_conditions');

insert into public.legal_sections (document_id, section_number, title, body, display_order, is_active)
select d.id, s.idx::int, s.section->'title', s.section->'body', (s.idx * 10)::int, true
from public.legal_documents d
cross join (
  select row_number() over () as idx, value as section
  from jsonb_array_elements($$[
    {"title":{"en":"Free Estimate","fr":"Presupuesto Gratuito"},"body":{"en":"We begin with a consultation to understand your space, your goals, and the level of service that best fits your project. Your estimate is an initial evaluation and may evolve based on final selections, site conditions, and project details. Estimates are typically valid for a limited period due to potential changes in material costs and availability.","fr":"Empezamos con una consulta para entender tu espacio, tus objetivos y el nivel de servicio que mejor se adapta a tu proyecto. El presupuesto es una evaluación inicial que puede evolucionar según las elecciones finales, las condiciones del sitio y los detalles del proyecto. Los presupuestos suelen ser válidos durante un periodo limitado debido a posibles variaciones en los costes y la disponibilidad de los materiales."}},
    {"title":{"en":"Project Validation","fr":"Validación del Proyecto"},"body":{"en":"A project is considered ready once the following are clearly defined: selected service level; confirmed layout and design direction; estimated budget and main components. Once validated, we move into planning and execution.","fr":"Un proyecto se considera listo cuando los siguientes elementos están claramente definidos: nivel de servicio elegido; distribución y dirección de diseño confirmadas; presupuesto estimado y componentes principales. Una vez validado, pasamos a la planificación y la ejecución."}},
    {"title":{"en":"Scope of Work & Service Levels","fr":"Alcance y Niveles de Servicio"},"body":{"en":"Each service includes only what is clearly defined within the selected level: Garage Design & Build Plan → planning and visual design; Design & Setup → design, sourcing, and preparation; Full Transformation → full coordination and execution; Smart Integration → technical systems and upgrades. Any request outside the selected service is handled as a project adjustment.","fr":"Cada servicio incluye únicamente lo que está claramente definido en el nivel elegido: Garage Design & Build Plan → planificación y diseño; Design & Setup → diseño, sourcing y preparación; Transformación Completa → coordinación y ejecución completas; Smart Integration → sistemas técnicos y mejoras. Cualquier solicitud fuera del servicio elegido se trata como un ajuste de proyecto."}},
    {"title":{"en":"Design Visuals","fr":"Visuales de Diseño"},"body":{"en":"Our 3D visuals and renderings are designed to help you clearly visualize your future space and make confident decisions. They represent the overall design intent, layout, and atmosphere of your project. As every garage is unique, small variations may occur in the final result due to materials, lighting, site conditions, or product availability. Our goal is always to stay as close as possible to the approved design while adapting to real-world conditions.","fr":"Nuestras imágenes 3D y renders están pensados para ayudarte a visualizar con claridad tu futuro espacio y tomar decisiones con confianza. Representan la intención de diseño, la distribución y la atmósfera de tu proyecto. Como cada garaje es único, pueden producirse pequeñas variaciones en el resultado final debido a los materiales, la iluminación, las condiciones del sitio o la disponibilidad de los productos. Nuestro objetivo es siempre acercarnos lo máximo posible al diseño aprobado, adaptándonos a las condiciones reales."}},
    {"title":{"en":"Design Approval","fr":"Aprobación del Diseño"},"body":{"en":"Before moving forward, you'll review and approve your design, including layout, materials, and overall concept. This step ensures everything is aligned with your vision before we begin sourcing or execution. Once approved, your project moves forward based on these validated plans. Any changes made afterward are considered project adjustments and may affect the timeline and pricing. We encourage you to review every detail carefully — this is your opportunity to make sure everything feels right before we build.","fr":"Antes de avanzar, revisarás y aprobarás tu diseño, incluida la distribución, los materiales y el concepto general. Este paso garantiza que todo esté alineado con tu visión antes de iniciar el sourcing o la ejecución. Una vez aprobado, el proyecto avanza según estos planos validados. Cualquier cambio posterior se considera un ajuste de proyecto y puede afectar a los plazos y al precio. Te animamos a revisar cada detalle con atención — es tu oportunidad para asegurarte de que todo encaja antes de construir."}},
    {"title":{"en":"Use of Designs & Intellectual Property","fr":"Uso de los Diseños y Propiedad Intelectual"},"body":{"en":"All layouts, technical plans, renderings, visual concepts, and design documents created by Garage à la Carte remain the intellectual property of Garage à la Carte unless otherwise agreed in writing. These materials are provided for the personal use of your project and may not be reproduced, sold, distributed, or used for commercial purposes without prior authorization. If you move forward with a signed Garage à la Carte project contract, your service fee may be credited in accordance with the terms of your selected service. If you choose to build independently or work with another contractor, a separate design usage or release agreement may be required before project documents are transferred for execution.","fr":"Todos los planos, planos técnicos, renders, conceptos visuales y documentos de diseño creados por Garage à la Carte siguen siendo propiedad intelectual de Garage à la Carte salvo acuerdo escrito en sentido contrario. Estos materiales se proporcionan para el uso personal de tu proyecto y no pueden reproducirse, venderse, distribuirse ni utilizarse con fines comerciales sin autorización previa. Si avanzas con un contrato de proyecto firmado con Garage à la Carte, tus honorarios pueden acreditarse según las condiciones del servicio elegido. Si decides construir por tu cuenta o trabajar con otro contratista, puede requerirse un acuerdo de uso o cesión de diseño antes de transferir los documentos del proyecto para su ejecución."}},
    {"title":{"en":"Client Responsibilities","fr":"Responsabilidades del Cliente"},"body":{"en":"To ensure your project runs smoothly, you agree to: provide accurate information about your space and needs; review and approve designs in a timely manner; ensure access to the property for delivery or installation; obtain any required approvals (HOA, building management, etc.). Utilities (electrical, plumbing, etc.) must be accessible and compliant prior to installation unless otherwise agreed.","fr":"Para que tu proyecto se desarrolle sin contratiempos, te comprometes a: facilitar información precisa sobre tu espacio y tus necesidades; revisar y aprobar los diseños con rapidez; garantizar el acceso a la propiedad para la entrega o la instalación; obtener las autorizaciones necesarias (HOA, administración del edificio, etc.). Los suministros (electricidad, fontanería, etc.) deben estar accesibles y en regla antes de la instalación, salvo acuerdo en sentido contrario."}},
    {"title":{"en":"Site Readiness & Decluttering","fr":"Preparación del Sitio"},"body":{"en":"Before delivery or installation, the garage must be fully prepared: personal items removed; workspace cleared; access unobstructed. Decluttering and item removal remain the client's responsibility. If the site is not ready, the project may be delayed or rescheduled, and additional costs may apply.","fr":"Antes de la entrega o la instalación, el garaje debe estar totalmente preparado: objetos personales retirados; espacio de trabajo despejado; acceso libre. El despeje y la retirada de objetos son responsabilidad del cliente. Si el sitio no está listo, el proyecto puede retrasarse o reprogramarse, y pueden aplicarse costes adicionales."}},
    {"title":{"en":"Site Documentation (Internal Use)","fr":"Documentación del Sitio (Uso Interno)"},"body":{"en":"To ensure a smooth and accurate process, we may take photos or short videos of your garage during on-site visits. This allows our team — including Guillaume and Juliette — to capture important details without requiring additional visits, helping us plan and execute your project efficiently. These materials are used strictly for internal purposes and remain private. They are never used for marketing without your prior approval (see Portfolio Use).","fr":"Para garantizar un proceso fluido y preciso, podemos tomar fotos o vídeos cortos de tu garaje durante las visitas. Esto permite a nuestro equipo — incluidos Guillaume y Juliette — capturar detalles importantes sin necesidad de visitas adicionales, ayudándonos a planificar y ejecutar tu proyecto con eficiencia. Estos materiales se utilizan estrictamente con fines internos y permanecen privados. Nunca se usan con fines de marketing sin tu autorización previa (ver Uso del Portfolio)."}},
    {"title":{"en":"Installation & Responsibility","fr":"Instalación y Responsabilidad"},"body":{"en":"Execution depends on your selected service level: Garage Design & Build Plan → client-managed execution; Design & Setup → client installs or requests support; Full Transformation → installation managed by our team and partners.","fr":"La ejecución depende del nivel de servicio elegido: Garage Design & Build Plan → ejecución gestionada por el cliente; Design & Setup → el cliente instala o solicita apoyo; Transformación Completa → instalación gestionada por nuestro equipo y socios."}},
    {"title":{"en":"Permits & Regulations","fr":"Permisos y Normativa"},"body":{"en":"Some projects may require permits depending on the scope and local regulations. Unless otherwise included, the client is responsible for obtaining permits. We provide guidance or coordination when part of the selected service.","fr":"Algunos proyectos pueden requerir permisos según el alcance y la normativa local. Salvo que se incluya, el cliente es responsable de obtener los permisos. Ofrecemos orientación o coordinación cuando forma parte del servicio elegido."}},
    {"title":{"en":"Licensed Trades","fr":"Profesionales Acreditados"},"body":{"en":"When required, we coordinate with qualified and licensed professionals to ensure compliance and quality.","fr":"Cuando es necesario, coordinamos con profesionales cualificados y acreditados para garantizar el cumplimiento y la calidad."}},
    {"title":{"en":"Project Timeline","fr":"Plazos del Proyecto"},"body":{"en":"Timelines are estimated and may be influenced by: material availability; supplier delays; weather conditions; permits and approvals; site readiness. We communicate any updates as early as possible.","fr":"Los plazos son estimativos y pueden verse afectados por: la disponibilidad de materiales; los retrasos de los proveedores; la meteorología; los permisos y autorizaciones; la preparación del sitio. Comunicamos cualquier actualización lo antes posible."}},
    {"title":{"en":"Payment Terms","fr":"Condiciones de Pago"},"body":{"en":"A deposit is required to secure your project and begin planning. The payment structure depends on your selected service and project scope and is defined during your project setup. It typically includes an initial deposit, progress payments, and a final balance prior to completion. No work begins without confirmed payment.","fr":"Se requiere un anticipo para asegurar tu proyecto e iniciar la planificación. La estructura de pago depende del servicio elegido y del alcance del proyecto, y se define durante la configuración del proyecto. Suele incluir un anticipo inicial, pagos parciales y un saldo final antes de la finalización. Ningún trabajo se inicia sin pago confirmado."}},
    {"title":{"en":"Project Adjustments","fr":"Ajustes del Proyecto"},"body":{"en":"Any change after approval is handled as a project adjustment. Adjustments may impact pricing, timeline, and delivery conditions, and are confirmed before moving forward.","fr":"Cualquier cambio tras la aprobación se gestiona como un ajuste de proyecto. Los ajustes pueden afectar al precio, los plazos y las condiciones de entrega, y se confirman antes de avanzar."}},
    {"title":{"en":"Existing Conditions","fr":"Condiciones Existentes"},"body":{"en":"We are not responsible for pre-existing issues such as structural defects, electrical or plumbing problems, or hidden damage. If identified, solutions may be proposed as part of an updated scope.","fr":"No somos responsables de problemas preexistentes como defectos estructurales, problemas eléctricos o de fontanería, o daños ocultos. Si se detectan, pueden proponerse soluciones como parte de un alcance actualizado."}},
    {"title":{"en":"Product Availability","fr":"Disponibilidad de Productos"},"body":{"en":"If a product becomes unavailable, we may recommend equivalent alternatives in quality and function, subject to your approval.","fr":"Si un producto deja de estar disponible, podemos recomendar alternativas equivalentes en calidad y función, sujetas a tu aprobación."}},
    {"title":{"en":"External Factors","fr":"Factores Externos"},"body":{"en":"Delays may occur due to factors beyond our control, including severe weather, supply chain disruptions, or regulatory constraints. We adapt and communicate as needed.","fr":"Pueden producirse retrasos por factores ajenos a nuestro control, como condiciones meteorológicas severas, interrupciones en la cadena de suministro o restricciones normativas. Nos adaptamos y comunicamos según sea necesario."}},
    {"title":{"en":"Delivery Area","fr":"Zona de Servicio"},"body":{"en":"On-site visits are available throughout the Orlando area. Visits beyond our standard zone are quoted based on location.","fr":"Las visitas in situ están disponibles en toda la zona de Orlando. Las visitas fuera de nuestra zona estándar se presupuestan según la ubicación."}},
    {"title":{"en":"Final Walkthrough","fr":"Visita Final"},"body":{"en":"For managed projects, a final walkthrough may be conducted to ensure everything aligns with the agreed plan.","fr":"En los proyectos gestionados, puede realizarse una visita final para asegurar que todo coincide con el plan acordado."}},
    {"title":{"en":"Cancellation","fr":"Cancelación"},"body":{"en":"Custom work and orders may not be canceled once initiated. Work completed up to the time of cancellation remains payable.","fr":"Los trabajos y pedidos personalizados no pueden cancelarse una vez iniciados. El trabajo realizado hasta el momento de la cancelación sigue siendo facturable."}},
    {"title":{"en":"Warranty","fr":"Garantía"},"body":{"en":"Manufacturer warranties apply to products. The installation warranty applies when installation is handled by our team or partners.","fr":"Las garantías del fabricante se aplican a los productos. La garantía de instalación se aplica cuando la instalación es gestionada por nuestro equipo o socios."}},
    {"title":{"en":"Portfolio Use","fr":"Uso del Portfolio"},"body":{"en":"We may use project photos for portfolio and marketing purposes unless you request otherwise in writing.","fr":"Podemos usar fotos del proyecto con fines de portfolio y marketing, salvo solicitud escrita en sentido contrario."}},
    {"title":{"en":"Our Commitment","fr":"Nuestro Compromiso"},"body":{"en":"Clear communication. Thoughtful design. Reliable coordination. Results aligned with your expectations.","fr":"Comunicación clara. Diseño cuidado. Coordinación fiable. Resultados alineados con tus expectativas."}}
  ]$$::jsonb)
) as s
where d.document_key = 'project_conditions';

-- Vérification (optionnel)
-- select section_number, title->>'en' from public.legal_sections
--   where document_id = (select id from public.legal_documents where document_key = 'project_conditions')
--   order by section_number;
